# This is a single-shot configuration that creates the entire Docker Voting app
# all in one go.
apiVersion: core.oam.dev/v1alpha1
kind: ApplicationConfiguration
metadata:
  name: voter-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  components:
    - componentName: db
      instanceName: db
      parameterValues: 
       - name: POSTGRES_PASSWORD
         value: P@ssw0rd
       - name: POSTGRES_HOST_AUTH_METHOD
         value: trust
    - componentName: redis
      instanceName: redis
    - componentName: worker
      instanceName: worker
    - componentName: frontend
      instanceName: frontend
      parameterValues:
       - name: OPTION_A
         value: K8s
       - name: OPTION_B
         value: Rudr
      traits:
        - name: ingress
          properties:
                  hostname: voting.wiprocms.com
                  path: /
                  servicePort: 80
    - componentName: admin
      instanceName: admin
